model:
  name: resnet50_v1_5
  framework: onnxrt_integerops
  inputs: []
  outputs: []
device: cpu
evaluation:
  performance:
    warmup: 10
    iteration: 1000
    configs:
      cores_per_instance: 4
      num_of_instance: 1
      kmp_affinity: granularity=fine,verbose,compact,1,0
    dataloader:
      batch_size: 1
      dataset:
        ImagenetRaw:
          data_path: images
          image_list: label.txt
      transform:
        Rescale: {}
        Resize:
          size: 256
        CenterCrop:
          size: 224
        Normalize:
          mean:
          - 0.485
          - 0.456
          - 0.406
          std:
          - 0.229
          - 0.224
          - 0.225
        Transpose:
          perm:
          - 2
          - 0
          - 1
        Cast:
          dtype: float32
      last_batch: rollover
      distributed: false
      shuffle: false
  accuracy:
    dataloader: null
